### ISSUE TITLE
Object gets cached to disk even when it exceeds max size

### ISSUE THREAD

**Issue by mattwarkentin** [r-lib/cachem#14]
Hi @wch,

Is this behaviour expected?
``` r
library(cachem)
library(lobstr)

mem_size <- 5e4

xx <- matrix(rnorm(1e6), nrow = 1000)
obj_size(xx)
#> 8,000,216 B

cm <- cache_mem(max_size = mem_size)
cm$set("x", xx)
cm$keys()
#> character(0)

cd <- cache_disk(dir = tempdir(), max_size = mem_size)
cd$set("x", xx)
cd$keys()
#> [1] "x"

cd$set("y", mtcars)
cd$keys()
#> [1] "x" "y"
```

**Comment by wch** [comment]
There was an off-by-one error when checking the throttle counter, which I've fixed in #15. 

After the fix, the behavior is now:

```R
cd <- cache_disk(dir = tempdir(), max_size = mem_size, prune_rate = 1)
cd$set("x", xx)
cd$keys()
#> character(0)

cd$set("y", mtcars)
cd$keys()
#> [1] "y"
```

Also note that for `cache_disk`, the pruning is throttled for performance reasons, so the `max_size` is not a hard limit:
https://github.com/r-lib/cachem/blob/82d9e6901d0def409f47bfdd4e5fc9fffa47bb90/R/cache-disk.R#L38-L42
