### ISSUE TITLE
Avoid set key if value exceed max size

### ISSUE THREAD

**Issue by dipterix** [r-lib/cachem#32]
```r
cache <- cachem::cache_mem(max_size = 1024)
cache$set('a', 1)
cache$set('b', 2)
cache$set('c', rnorm(1000))
cache$size()
```

Setting `c` will remove everything in the cache. Would it be nicer if `c` is never set (since it's larger than the `max_size`)?

In current implementation, neither `lru` nor `fifo` can avoid cache getting wiped out...

**Comment by wch** [comment]
I think that the current behavior of the cache makes sense according to `lru` and `fifo`.

You've identified a possible optimization for an edge case, but there are a lot of possible edge cases. For example:

```R
cache <- cachem::cache_mem(max_size = 1024)
cache$set('a', 1)
cache$keys()
#> [1] "a"

cache$set('b', 1:200)
cache$keys()
#> [1] "b" "a"

cache$set('c', 1:100)
cache$keys()
#> [1] "c"
```

One could argue that it should be optimized so that when `c` is added, only `b` should be removed, instead of both `a` and `b`. However, if you follow this line of reasoning, then you could end up with a cache where small objects almost never get pruned, even if they are much older than larger objects in the cache.

My overall point is that there's a trade-off between:
* trying to optimize the performance
* simplicity and predictability

Although it would be possible to implement the optimization you're describing, that kind of case is pretty unusual, and it's better overall to stay with the current behavior. One could reasonably disagree, though.

If this is posing problems in your particular use case, it would be simple to write a wrapper for `cache_mem` which implements the behavior you're describing.

**Comment by dipterix** [comment]
I see, I guess what I want was to prioritize removing largest cache first, which is not lru nor fifo. Thanks for explanation. I will write a wrapper.

**Comment by wch** [comment]
Sounds good -- just keep in mind that if you always prioritize removing the largest object, then you will end up with a cache where the largest object always is pruned first, and small objects may stay around forever, as I described in my example above.

**Comment by dipterix** [comment]
Thanks, this is very constructive advice 😃
